version: "3.9"
  #networks:
  #grafana: {}
configs:
  agent.yaml:
    file: docker/agent.yaml

volumes:
  grafana: {}
  tempo: {}
  loki: {}
  agent: {}

services:
  agent:
    image: grafana/agent
    volumes:
      - agent:/agent
    ports:
      - "12347:12347" # HTTP ingester
    command:
      - "-config.file=/agent.yaml"
      - "-enable-features=integrations-next"
      - "-config.expand-env=true"
    configs:
      - agent.yaml
  tempo:
    image: grafana/tempo
    volumes:
      - tempo:/traces
    command:
      - "-server.http-listen-port=3100"
      - "-storage.trace.backend=local"
      - "-storage.trace.local.path=/traces"
    ports:
      - "4317:4317" # gRPC
  loki:
    image: grafana/loki
    command:
      - "-server.http-listen-address=0.0.0.0"
      - "-config.file=/etc/loki/local-config.yaml"
    volumes:
      - loki:/loki
      #ports:
      #- "3100:3100" # HTTP
      #- "9095:9095" # gRPC
  grafana:
    image: grafana/grafana:9.4.9
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - grafana:/var/lib/grafana
      - ./docker/grafana-datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3500:3000"
