apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: {{ namespace }}
  name: tracing-demo-frontend
  namespace: {{ namespace }}
spec:
  image: {{ frontend_image }}
  frontend:
    generatedConfig:
      mountPath: /usr/share/nginx/html/nais.js
  ingresses:
  - {{ ingress }}
  port: 8080
  replicas:
    cpuThresholdPercentage: 50
    max: 1
    min: 1
---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: {{ namespace }}
  name: tracing-demo-backend
  namespace: {{ namespace }}
spec:
  image: {{ backend_image }}
  ingresses:
  - {{ ingress }}/api
  env:
  - name: "ENDPOINT"
    value: "tempo-distributor.nais-system:4317"
  - name: "LISTEN_ADDR"
    value: "0.0.0.0:8080"
  port: 8080
  replicas:
    cpuThresholdPercentage: 50
    max: 1
    min: 1
