apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: kimfoo
  name: tracing-demo
  namespace: kimfoo
spec:
  image: {{ image }}
  ingresses:
  - https://tracing-demo.dev.dev-nais.cloud.nais.io
  port: 3000
  replicas:
    cpuThresholdPercentage: 50
    max: 1
    min: 1
