{
 "title": "Frontend web vitals",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app",
    "query": {}
   },
   { "name": "env", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Event log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{kind=\"event\"} | logfmt"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "TTFB",
   "type": "stat",
   "description": "Time to First Byte (TTFB) is a foundational metric for measuring connection setup time and web server responsiveness in both the lab and the field. It helps identify when a web server is too slow to respond to requests. In the case of navigation requests—that is, requests for an HTML document—it precedes every other meaningful loading performance metric.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app_name=\"$app\"} |= \"ttfb\" | logfmt | unwrap ttfb [$__range]) by (app)",
     "legendFormat": "TTFB"
    }
   ]
  },
  {
   "title": "FCP",
   "type": "stat",
   "description": "First Contentful Paint (FCP) is an important, user-centric metric for measuring perceived load speed because it marks the first point in the page load timeline where the user can see anything on the screen—a fast FCP helps reassure the user that something is happening.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app_name=\"$app\"} |= \" fcp=\" | logfmt | unwrap fcp [$__range]) by (app)",
     "legendFormat": "FCP"
    }
   ]
  },
  {
   "title": "CLS",
   "type": "stat",
   "description": "Cumulative Layout Shift\n\nCumulative Layout Shift is the newest of the 3 Core Web Vitals. The CLS metric observes how many visible elements on a webpage shift around as the page loads, and by how much. What is more frustrating than clicking a button on a page just for the button to shift down as more of the page loads and you instead click an ad? \n\nThe Cumulative Layout Shift metric uses multiple frames of the page as it loads to determine when the elements shift and by how much. Anything below 0.1 is a ‘Good’ score, anything between 0.1 and 0.25 ‘Needs Improvement’, and any score over 0.25 is ‘Poor’. ",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app_name=\"$app\"} |= \"cls\" | logfmt | unwrap cls [$__range]) by (app)",
     "legendFormat": "CLS"
    }
   ]
  },
  {
   "title": "LCP",
   "type": "stat",
   "description": "Largest Contentful Paint\n\nLargest Contentful Paint refers to the loading performance of a site. Largest Contentful Paint does not measure the time it takes for a site to fully load, but rather the largest content element on the page. This can be an image, video, animation, game, etc.\n\nIf a page has some text, a small image, and a large video, the video would be the largest element. The largest content element on the page is usually the centerpiece and therefore optimising it to load quicker leads to a better experience. ",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app_name=\"$app\"} |= \" lcp=\" | logfmt | unwrap lcp [$__range]) by (app)",
     "legendFormat": "LCP"
    }
   ]
  },
  {
   "title": "FID",
   "type": "stat",
   "description": "First Input Delay\n\nFirst Input Delay is a test to measure the time it takes for a browser to acknowledge the user’s first interaction on the page. A quicker response time leads to a better user experience that feels competent and satisfying. After all, who wants to be on a site with the page fully loaded and wait, for what feels like forever, when you click a link? \n\nBrowsers are working harder than ever as sites become increasingly complex. The First Input Delay measures mouse clicks, trackpad taps, and key presses that require the browser to respond. A First Input Delay score of anything under 100 ms scores ‘Good’, 100 ms – 300 ms scores ‘Needs Improvement’, and anything above 300 ms is scored ‘Poor’. ",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app_name=\"$app\"} |= \" fid=\" | logfmt | unwrap fid [$__range]) by (app)",
     "legendFormat": "FID"
    }
   ]
  },
  {
   "title": "Page Load, p75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",app_name=\"$app\"} |= \" ttfb=\" | logfmt | unwrap ttfb [5m]) by (app)",
     "legendFormat": "TTFB"
    },
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",app_name=\"$app\"} |= \" fcp=\" | logfmt | unwrap fcp [5m]) by (app)",
     "legendFormat": "FCP"
    },
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",app_name=\"$app\"} |= \" lcp=\" | logfmt | unwrap lcp [5m]) by (app)",
     "legendFormat": "LCP"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift, p75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",app_name=\"$app\"} |= \" cls=\" | logfmt | unwrap cls [5m]) by (app)",
     "legendFormat": "CLS"
    }
   ]
  },
  {
   "title": "First Input Delay, p75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",app_name=\"$app\"} |= \" fid=\" | logfmt | unwrap fid [5m]) by (app)",
     "legendFormat": "FID"
    }
   ]
  },
  { "title": "Exceptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app_name=\"$app\",kind=\"exception\"} [$__range])) by (app)"
    }
   ]
  },
  {
   "title": "Exceptions Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 2, "y": 21 },
   "targets": [
    {
     "expr": "count_over_time({app_name=\"$app\",kind=\"exception\"} [$__interval])",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Top Exceptions",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 21 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({kind=\"exception\", app_name=\"$app\"} | logfmt [$__range])) by (value))"
    }
   ]
  },
  {
   "title": "Top URLs by Exception Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({kind=\"exception\", app_name=\"$app\"} | logfmt [$__range])) by (page_url))"
    }
   ]
  },
  {
   "title": "Top Browsers by Exception Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 14, "y": 29 },
   "targets": [
    {
     "expr": "topk(10, count by (browser_name, browser_version) (count_over_time({kind=\"exception\", app_name=\"$app\"} | logfmt [$__range])))"
    }
   ]
  },
  { "title": "Meta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Popular Browsers",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({app_name=\"$app\",kind=\"measurement\"} |= \" ttfb=\" | logfmt [$__range])) by (browser_name, browser_version))"
    }
   ]
  },
  {
   "title": "Visits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 10, "y": 39 },
   "targets": [
    {
     "expr": "count_over_time({app_name=\"$app\",kind=\"measurement\"} |= \" ttfb=\" [$__interval])",
     "legendFormat": "visits"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Top Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({kind=\"event\", app_name=\"$app\"} | logfmt [$__range])) by (event_name))"
    }
   ]
  }
 ]
}