# vi: se et:

name: Build and deploy image
on:
  push:
    branches:
      - main
    paths-ignore:
      - "charts/**"
env:
  REGISTRY: europe-north1-docker.pkg.dev/nais-io/nais/images
jobs:
  build_push_sign_webapp:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3
      - uses: nais/platform-build-push-sign@main
        with:
          name: tracing-demo-frontend
          dockerfile: ./webapp/Dockerfile
          google_service_account: gh-unleash
          push: ${{ github.actor != 'dependabot[bot]' }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
  build_push_sign_backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3
      - uses: nais/platform-build-push-sign@main
        with:
          name: tracing-demo-backend
          dockerfile: ./backend/Dockerfile
          google_service_account: gh-unleash
          push: ${{ github.actor != 'dependabot[bot]' }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
  rollout:
    permissions:
      id-token: write
    name: Deploy to NAIS
    needs: ["build_push_sign_webapp", "build_push_sign_backend"]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - uses: nais/deploy/actions/deploy@v1
      env:
        DEPLOY_SERVER: deploy.nav.cloud.nais.io:443
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        RESOURCE: nais.yaml
        PRINT_PAYLOAD: "true"
        VAR: backend-image=${{ env.REGISTRY }}/tracing-demo-backend:${{ needs.build_push_sign_backend.outputs.version }},frontend-image=${{ env.REGISTRY }}/tracing-demo-frontend:${{ needs.build_push_sign_webapp.outputs.version }},ingress=https://tracing-demo.intern.dev.nav.no,namespace=aura
    - uses: nais/deploy/actions/deploy@v1
      env:
        DEPLOY_SERVER: deploy.dev-nais.cloud.nais.io:443
        APIKEY: ${{ secrets.DEPLOY_DEV_NAIS_DEV_KIMFOO }}
        CLUSTER: dev
        RESOURCE: nais.yaml
        PRINT_PAYLOAD: "true"
        VAR: backend-image=${{ env.REGISTRY }}/tracing-demo-backend:${{ needs.build_push_sign_backend.outputs.version }},frontend-image=${{ env.REGISTRY }}/tracing-demo-frontend:${{ needs.build_push_sign_webapp.outputs.version }},ingress=https://tracing-demo.dev.nav.cloud.nais.io,namespace=kimfoo
